### ISSUE TITLE
No cluster or repair with hammer of the core

### ISSUE THREAD

**Issue by jrpoints** [VapourDrive/Hammerz#12]
I put together a hammer of the core and am not receiving clusters as I believe I should be. I also tried to put a repair II book on it and it wouldn't let me.

**Comment by ColinGBos** [comment]
https://github.com/Azanor/thaumcraft-5-api/issues/8 is the reason for not being able to put repair on it, and I can't really do anything about it but wait (joys of closed src mods).
I'll have a look at the clusters not dropping but probably no release for a few days as I have a lot of Real Life things happening at the moment.
