### ISSUE TITLE
Crash when disabling vanilla hammers in config.

### ISSUE THREAD

**Issue by YurgenJurgensen** [VapourDrive/Hammerz#13]
Removing a vanilla hammer in the config removes the item but the recipe remains.  Attempting to craft the recipe causes the following crash.
[crash-2016-02-25_22.08.05-client.txt](https://github.com/VapourDrive/Hammerz/files/147361/crash-2016-02-25_22.08.05-client.txt)

**Comment by ColinGBos** [comment]
Is this the 1.8.9 version or the 1.7.10 version?

**Comment by YurgenJurgensen** [comment]
1.7.10

**Comment by ColinGBos** [comment]
Alright, I'll have a look when I can and push a fix. Thanks for the report!
