### ISSUE TITLE
Compatibility request for Better With Mods

### ISSUE THREAD

**Issue by Vazkii** [VapourDrive/Hammerz#17]
Better With Mods adds Soulforged Steel as an endgame (-ish) material. Requesting that hammers can be made using it.

https://minecraft.curseforge.com/projects/better-with-mods

**Comment by ColinGBos** [comment]
This could happen yeah, will have some time to work on stuff this coming weekend.

**Comment by ColinGBos** [comment]
Closed... after a long wait
