### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by zedner** [VapourDrive/Hammerz#2]

**Comment by zedner** [comment]
Time: 23.12.15. 20.10
Description: Rendering item

java.lang.ClassCastException: vapourdrive.hammerz.items.DarkHammer cannot be cast to cofh.api.energy.IEnergyContainerItem
    at vapourdrive.hammerz.items.PoweredItemRenderer.renderToInventory(PoweredItemRenderer.java:70)
    at vapourdrive.hammerz.items.PoweredItemRenderer.renderItem(PoweredItemRenderer.java:40)
    at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:202)
    at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
    at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:489)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at vapourdrive.hammerz.items.PoweredItemRenderer.renderToInventory(PoweredItemRenderer.java:70)
    at vapourdrive.hammerz.items.PoweredItemRenderer.renderItem(PoweredItemRenderer.java:40)
    at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:202)

-- Item being rendered --
Details:
    Item Type: vapourdrive.hammerz.items.DarkHammer@4f7b9af9
    Item Aux: 0
    Item NBT: {hammerz.upgrade.empowerment:4,hammerz.hammer.energy:25000000}
    Item Foil: false
Stacktrace:
    at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
    at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:489)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)

-- Screen render details --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
    Mouse location: Scaled: (291, 307). Absolute: (583, 283)
    Screen size: Scaled: (640, 449). Absolute: (1280, 898). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Zednerr'/227, l='MpServer', x=148.31, y=65.62, z=260.42]]
    Chunk stats: MultiplayerChunkCache: 529, 538
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (232,64,208), Chunk: (at 8,4,0 in 14,13; contains blocks 224,0,208 to 239,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 913899 game time, 275679 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 66 total; [EntityCreeper['Creeper'/128, l='MpServer', x=174.50, y=60.00, z=192.50], EntityCreeper['Creeper'/129, l='MpServer', x=171.50, y=60.00, z=192.50], EntityCreeper['Creeper'/130, l='MpServer', x=174.50, y=60.00, z=193.50], EntityCreeper['Creeper'/131, l='MpServer', x=172.50, y=60.00, z=193.50], EntityCreeper['Creeper'/132, l='MpServer', x=167.50, y=57.00, z=198.50], EntityHorse['Horse'/133, l='MpServer', x=166.06, y=67.00, z=198.34], EntitySkeleton['Skeleton'/134, l='MpServer', x=160.50, y=41.00, z=340.50], EntityZombie['Zombie'/139, l='MpServer', x=185.50, y=54.00, z=190.50], EntityZombie['Zombie'/140, l='MpServer', x=183.50, y=54.00, z=190.50], EntityHorse['Horse'/141, l='MpServer', x=185.25, y=66.00, z=203.50], EntityBat['Bat'/142, l='MpServer', x=182.59, y=18.10, z=262.75], EntityChicken['Chicken'/143, l='MpServer', x=190.56, y=63.00, z=291.44], EntityChicken['Chicken'/144, l='MpServer', x=185.59, y=64.00, z=300.63], EntityChicken['Chicken'/17, l='MpServer', x=73.16, y=67.00, z=326.41], EntityChicken['Chicken'/18, l='MpServer', x=73.59, y=67.00, z=331.84], EntityChicken['Chicken'/19, l='MpServer', x=73.25, y=67.00, z=334.56], EntityChicken['Chicken'/20, l='MpServer', x=78.81, y=67.00, z=336.25], EntityHorse['Horse'/152, l='MpServer', x=206.88, y=69.00, z=201.59], EntityHorse['Horse'/153, l='MpServer', x=195.34, y=64.00, z=228.00], EntityChicken['Chicken'/154, l='MpServer', x=199.31, y=62.39, z=263.84], EntityChicken['Chicken'/155, l='MpServer', x=207.53, y=64.00, z=307.91], EntityHorse['Horse'/161, l='MpServer', x=221.13, y=65.00, z=231.00], EntityChicken['Chicken'/162, l='MpServer', x=218.16, y=62.48, z=309.16], EntityChicken['Chicken'/163, l='MpServer', x=208.06, y=64.00, z=304.28], EntityCow['Cow'/35, l='MpServer', x=92.84, y=69.00, z=240.06], EntityCreeper['Creeper'/42, l='MpServer', x=108.69, y=59.00, z=205.50], EntityHorse['Horse'/170, l='MpServer', x=228.13, y=64.00, z=256.00], EntityZombie['Zombie'/43, l='MpServer', x=111.50, y=47.00, z=231.50], EntityCreeper['Creeper'/53, l='MpServer', x=114.50, y=56.00, z=211.50], EntityHorse['Horse'/55, l='MpServer', x=122.03, y=70.00, z=209.06], EntityBat['Bat'/56, l='MpServer', x=126.50, y=58.10, z=239.78], EntityCreeper['Creeper'/57, l='MpServer', x=125.50, y=56.00, z=233.03], EntityZombie['Zombie'/58, l='MpServer', x=115.63, y=43.00, z=256.31], EntityZombie['Zombie'/59, l='MpServer', x=109.41, y=48.00, z=271.03], EntityEnderman['Enderman'/60, l='MpServer', x=117.50, y=23.00, z=282.50], EntityZombie['Zombie'/61, l='MpServer', x=127.50, y=16.00, z=294.50], EntityCreeper['Creeper'/62, l='MpServer', x=126.50, y=42.00, z=298.50], EntitySpider['Spider'/63, l='MpServer', x=123.91, y=41.00, z=291.19], EntitySpider['Spider'/64, l='MpServer', x=122.84, y=41.00, z=292.97], EntityZombie['Zombie'/65, l='MpServer', x=133.03, y=42.00, z=290.50], EntityZombie['Zombie'/66, l='MpServer', x=123.50, y=41.00, z=289.50], EntityBat['Bat'/67, l='MpServer', x=136.86, y=53.22, z=303.65], EntitySpider['Spider'/69, l='MpServer', x=127.41, y=16.00, z=338.59], EntityCreeper['Creeper'/84, l='MpServer', x=142.59, y=34.00, z=218.06], EntityBat['Bat'/85, l='MpServer', x=142.72, y=22.10, z=224.31], EntityBat['Bat'/86, l='MpServer', x=140.22, y=24.10, z=243.53], EntityBat['Bat'/87, l='MpServer', x=143.75, y=58.10, z=264.25], EntityBat['Bat'/88, l='MpServer', x=142.50, y=58.10, z=264.97], EntityZombie['Zombie'/89, l='MpServer', x=140.34, y=14.00, z=285.66], EntityCreeper['Creeper'/90, l='MpServer', x=138.44, y=16.00, z=281.50], EntityZombie['Zombie'/91, l='MpServer', x=141.50, y=20.00, z=278.50], EntityZombie['Zombie'/92, l='MpServer', x=140.50, y=20.00, z=278.50], EntityCreeper['Creeper'/93, l='MpServer', x=138.50, y=20.00, z=277.50], EntityBat['Bat'/94, l='MpServer', x=137.52, y=21.21, z=276.46], EntityCreeper['Creeper'/95, l='MpServer', x=143.66, y=13.36, z=289.34], EntityClientPlayerMP['Zednerr'/227, l='MpServer', x=148.31, y=65.62, z=260.42], EntityCreeper['Creeper'/107, l='MpServer', x=150.50, y=29.00, z=195.50], EntityZombie['Zombie'/108, l='MpServer', x=151.50, y=21.00, z=235.50], EntityZombie['Zombie'/109, l='MpServer', x=154.13, y=29.00, z=229.50], EntitySkeleton['Skeleton'/110, l='MpServer', x=136.47, y=19.00, z=247.13], EntityBat['Bat'/111, l='MpServer', x=146.25, y=20.10, z=258.75], EntityCreeper['Creeper'/112, l='MpServer', x=155.50, y=16.00, z=319.50], EntityZombie['Zombie'/113, l='MpServer', x=149.34, y=30.00, z=339.50], EntityZombie['Zombie'/114, l='MpServer', x=148.47, y=30.00, z=338.91], EntityCreeper['Creeper'/115, l='MpServer', x=154.50, y=30.00, z=338.50], EntitySkeleton['Skeleton'/116, l='MpServer', x=150.31, y=30.00, z=339.47]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 313936384 bytes (299 MB) / 674213888 bytes (642 MB) up to 4281597952 bytes (4083 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_C1 46 mods loaded, 46 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1558} [Minecraft Forge](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.5.118} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    UCHIJAAAA   OpenModsCore{0.8} [OpenModsCore](minecraft.jar) 
    UCHIJAAAA   deconstruction{2.2.5} [The Deconstruction Mod]([MC1.7.10]deconstruction[v2.2.5].jar) 
    UCHIJAAAA   ActuallyAdditions{1.7.10-r15} [Actually Additions](ActuallyAdditions-1.7.10-r15.jar) 
    UCHIJAAAA   bdlib{1.9.2.102} [BD Lib](bdlib-1.9.2.102-mc1.7.10.jar) 
    UCHIJAAAA   CarpentersBlocks{3.3.7} [Carpenter's Blocks](Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
    UCHIJAAAA   ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   chisel{2.9.4.10} [Chisel](Chisel-2.9.4.10.jar) 
    UCHIJAAAA   creativecore{1.3.14} [CreativeCore](CreativeCore v1.3.19 mc1.7.10.jar) 
    UCHIJAAAA   cubicvillager{0.25} [Cubic Villager](CubicVillager-0.25.jar) 
    UCHIJAAAA   endercore{1.7.10-0.2.0.31_beta} [EnderCore](EnderCore-1.7.10-0.2.0.31_beta.jar) 
    UCHIJAAAA   EnderIO{1.7.10-2.3.0.422_beta} [Ender IO](EnderIO-1.7.10-2.3.0.422_beta.jar) 
    UCHIJAAAA   EnderStorage{1.4.7.37} [EnderStorage](EnderStorage-1.7.10-1.4.7.37-universal.jar) 
    UCHIJAAAA   ExtraUtilities{1.2.11} [Extra Utilities](extrautilities-1.2.11.jar) 
    UCHIJAAAA   fairylights{1.4.0} [Fairy Lights](fairylights-1.4.0-1.7.10.jar) 
    UCHIJAAAA   fastleafdecay{1.0} [Fast Leaf Decay](FastLeafDecay-1.7.10-1.0.jar) 
    UCHIJAAAA   FlatSigns{2.1.0.19} [Flat Signs](FlatSigns-1.7.10-universal-2.1.0.19.jar) 
    UCHIJAAAA   McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   hammertime{Hammer Time-1.7.10-1.3.2} [Hammer Time!](HammerTime-1.3.2.jar) 
    UCHIJAAAA   hammerz{0.1.5.27} [Hammerz](Hammerz-1.7.10-0.1.5.27.jar) 
    UCHIJAAAA   HelperToolsID{1.1.5M} [HelperTools](HelperTools-1.7.10-1.1.5M.jar) 
    UCHIJAAAA   inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UCHIJAAAA   IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCHIJAAAA   JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
    UCHIJAAAA   jacb{1.0.3} [JACB](JACB-1.7.10-1.0.3.jar) 
    UCHIJAAAA   koresample{1.7.10-1.2.5} [Kore Sample](KoreSample-1.7.10-1.2.5.jar) 
    UCHIJAAAA   littletiles{1.0.0} [LittleTiles](LittleTiles v1.0.0 mc1.7.10.jar) 
    UCHIJAAAA   Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat](Neat 1.0-1.jar) 
    UCHIJAAAA   OpenMods{0.8} [OpenMods](OpenModsLib-1.7.10-0.8.jar) 
    UCHIJAAAA   OpenBlocks{1.4.4} [OpenBlocks](OpenBlocks-1.7.10-1.4.4.jar) 
    UCHIJAAAA   PocketCraft{0.0.3} [PocketCraft](PocketCraft-1.7.2-0.0.3.jar) 
    UCHIJAAAA   pocketnether{1.4} [Pocket Nether Mod](pocketnether-1.7.10-1.4.jar) 
    UCHIJAAAA   qucra{1.7.10-1.6} [Quick Crafting](QuickCrafting-1.7.10-1.6.jar) 
    UCHIJAAAA   RedstonePasteMod{1.6.2} [Redstone Paste](RedstonePasteMod-1.7.10-1.6.2.jar) 
    UCHIJAAAA   satdismodid{1.0} [SaturationDisplay](SaturationDisplay-1.7.2-2.0.jar) 
    UCHIJAAAA   SimilsaxTranstructors{1.7.10.15} [Similsax Transtructors](SimilsaxTranstructors-1.7.10.15.jar) 
    UCHIJAAAA   SmartCursor{1.5.0} [SmartCursor](SmartCursor-1.5.0-MC1.7.10.jar) 
    UCHIJAAAA   wallpaper{0.9} [Wallpaper](wallpaper-0.9-1.7.10.jar) 
    UCHIJAAAA   witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) 
    UCHIJAAAA   YALSM{2.1.3} [Yet Another Leather Smelting Mod](yalsm-2.1.3.jar) 
    UCHIJAAAA   zyinhud{1.3.9} [Zyin's HUD](ZyinsHUD-%281.7.10%29-v.1.3.9.jar) 
    UCHIJAAAA   ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13416 Compatibility Profile Context 15.300.1025.1001' Renderer: 'AMD Radeon HD 7660D + HD 7700 Dual Graphics'
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    List of loaded APIs: 
        \* BuildCraftAPI|core (1.0) from extrautilities-1.2.11.jar
        \* BuildCraftAPI|tools (1.0) from extrautilities-1.2.11.jar
        \* CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.7 - MC 1.7.10.jar
        \* ChiselAPI (0.1.1) from Chisel-2.9.4.10.jar
        \* ChiselAPI|Carving (0.1.1) from Chisel-2.9.4.10.jar
        \* ChiselAPI|Rendering (0.1.1) from Chisel-2.9.4.10.jar
        \* CoFHAPI (1.7.10R1.0.2) from ActuallyAdditions-1.7.10-r15.jar
        \* CoFHAPI|block (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.422_beta.jar
        \* CoFHAPI|energy (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.422_beta.jar
        \* CoFHAPI|inventory (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.422_beta.jar
        \* CoFHAPI|item (1.7.10R1.0.13B1) from extrautilities-1.2.11.jar
        \* CoFHAPI|tileentity (1.7.10R1.0.13) from EnderIO-1.7.10-2.3.0.422_beta.jar
        \* CoFHAPI|transport (1.7.10R1.0.13) from EnderCore-1.7.10-0.2.0.31_beta.jar
        \* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.3.0.422_beta.jar
        \* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.3.0.422_beta.jar
        \* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.7.10-2.3.0.422_beta.jar
        \* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.3.0.422_beta.jar
        \* OpenBlocks|API (1.0) from OpenBlocks-1.7.10-1.4.4.jar
    Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
    EnderIO: Found the following problem(s) with your installation:
                  \* Optifine is installed. This is NOT supported.
                  \* The RF API that is being used (1.7.10R1.0.2 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.13 from EnderIO-1.7.10-2.3.0.422_beta.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
    Stencil buffer state: Function set: GL30, pool: internal, bits: 8
    Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 7660D + HD 7700 Dual Graphics GL version 4.5.13416 Compatibility Profile Context 15.300.1025.1001, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [Unity-Complete-1.2.0.zip]
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by ColinGBos** [comment]
Where was the item rendering when this crash happened?
What mod's do you all have installed?
- CoFHAPI (1.7.10R1.0.2) from ActuallyAdditions-1.7.10-r15.jar makes me a little suspicious as this is an out of date api being shipped with ActuallyAdditions.

I'll try to get a fix together, I should check if the item can be cast anyways >.>.

**Comment by zedner** [comment]
crash happened when i tried to open creative panel of hammerz mod, all mods are listed in crashlog, just optifine isn't listed.

**Comment by ColinGBos** [comment]
Ok, I figured it out, though I'm not really sure why it is an issue... I'm not entirely used to working with API's yet. EnderIO bundles part of the CoFH RF API and can use IContainerEnergyItem but apparently I can't. Not that it really mattered because I can make sure that the rendered Item is simply a hammer and get the needed info from there.
I'll push a fix soon.

**Comment by ColinGBos** [comment]
In the meantime, installing just CoFH core should fix the issue.

**Comment by zedner** [comment]
okay thanx
