### ISSUE TITLE
Research note not actually being added to inventory [0.1.6.32]

### ISSUE THREAD

**Issue by dirtyfargo** [VapourDrive/Hammerz#4]
Description: When attempting to unlock the research note for the Thaumium Hammer, it states that it added the research note to my inventory, however there is not one to be found. (As shown in the gif linked below)
https://gyazo.com/290add36e24e74a20a291a9dc4f3cb5b
Version: 0.1.6.32
Forge Version: 10.13.4.1614
:)

**Comment by ColinGBos** [comment]
Thanks for the bug submission, I am fairly new to using the api and Thaumcraft itself, and just learned the commands for testing out researches and the like. I found out what I was doing wrong, I was setting up the research to have no aspectlist which apparently you need. So now there is an aspect list to the research, and it works.
Pushing a fixed build after some finishing touches.

**Comment by dirtyfargo** [comment]
That makes sense, thanks for the quick reply and no problem =)
