### ISSUE TITLE
Repair with materials doesn't work

### ISSUE THREAD

**Issue by OnmyojiOmn** [VapourDrive/Hammerz#8]
Following up.

![2016-01-23_18 35 14](https://cloud.githubusercontent.com/assets/3220305/12534159/0f7c7c98-c201-11e5-8c47-d08267af1927.png)

Same with other materials. Sorry if I'm just not understanding something.

**Comment by ColinGBos** [comment]
Ah I understand your confusion, like regular tools they are repairable in the anvil. I'll potentially see about using the crafting event for adding in the two hammer = 1 repaired hammer but no guarantees.

**Comment by OnmyojiOmn** [comment]
Oof. Duh. Thanks for getting back to me so quickly.
